(function(){
'use strict';
const NAV=[['index.html','Home'],['all-plants.html','Plants'],['journal.html','Photo Journal'],['projects.html','Projects'],['garden-friends.html','Garden Friends'],['harvest-log.html','Harvest Log'],['calendar.html','Calendar']];
const EXTRA_SEARCH=[
  ['oregano herb garden vegetable','oregano.html','Oregano'],
  ['butternut squash winter squash vegetable','butternut-squash.html','Butternut Squash'],
  ['japanese pieris shrub evergreen','japanese-pieris.html','Japanese Pieris'],
  ['morning glory flower vine','morning-glory.html','Morning Glory'],
  ['jade string bean beans vegetable','jade-string-bean.html','Jade String Bean'],
  ['peony flower perennial','peony.html','Peony'],
  ['large jade big jade indoor plant','jade-cutting-project.html','Large Jade Plant'],
  ['small jade indoor plant','jade-cutting-project.html','Small Jade Plant'],
  ['sunflower flower garden','sunflower.html','Sunflower']
];
function isHome(){const p=location.pathname.replace(/\/+$/,'');return p===''||p.endsWith('/index.html')||p.endsWith('/Lou-s-plant-handbook');}
function file(){return location.pathname.split('/').pop()||'index.html';}
function active(){const f=file();if(f==='index.html')return'index.html';if(f==='all-plants.html'||f==='indoor-plants.html'||f==='garden-vegetables.html'||f==='fruit-berries.html'||f==='flowers-outdoor.html'||f==='trees-shrubs.html'||f.includes('plant')||f.includes('care')||f.includes('jade')||f.includes('peony')||f.includes('oregano')||f.includes('squash')||f.includes('pieris'))return'all-plants.html';if(f==='journal.html'||f.includes('journal')||f.includes('update')||f.includes('late-july')||f.includes('august-'))return'journal.html';if(f==='garden-friends.html'||f.includes('pollinator')||f.includes('friend')||f.includes('bird'))return'garden-friends.html';if(f==='harvest-log.html')return'harvest-log.html';if(f==='calendar.html')return'calendar.html';if(f==='projects.html'||f.includes('project')||f.includes('burns-bear')||f.includes('grape-arbor')||f.includes('poulin'))return'projects.html';return'';}
function header(){const h=document.querySelector('.site-header');if(!h)return;const a=active();h.innerHTML=`<div class="topbar lou-unified-topbar"><a class="brand" href="index.html" aria-label="Lou's Garden Guide home"><img src="icon-512.png?v=31" alt="Lou's Garden Guide"><div><strong>Lou’s Garden Guide</strong><span class="lou-brand-tagline">Grow beautiful. Live well.</span></div></a><div class="top-search lou-global-search"><input id="topSearch" type="search" placeholder="Search plants, pests, notes…" aria-label="Search Lou's Garden Guide" autocomplete="off"></div></div><nav aria-label="Main navigation"><div class="nav lou-main-nav">${NAV.map(([href,label])=>`<a href="${href}"${href===a?' class="active" aria-current="page"':''}>${label}</a>`).join('')}</div></nav>`;
if(!document.getElementById('louUnifiedNavStyles')){const s=document.createElement('style');s.id='louUnifiedNavStyles';s.textContent=`.site-header{background:#fffdf8!important;border-bottom:1px solid #d9ded1!important;position:sticky;top:0;z-index:1000}.lou-unified-topbar{max-width:1180px;margin:auto;display:flex;align-items:center;justify-content:space-between;gap:18px;padding:14px 18px!important}.lou-unified-topbar .brand{display:flex;align-items:center;gap:13px;text-decoration:none;min-width:0}.lou-unified-topbar .brand img{width:70px!important;height:70px!important;border-radius:15px;object-fit:cover;flex:none}.lou-unified-topbar .brand strong{display:block;color:#315d3f;font:700 clamp(1.4rem,3vw,2.05rem) Georgia,serif;white-space:nowrap}.lou-brand-tagline{display:block;font-size:.78rem;letter-spacing:.12em;color:#68806a;text-transform:uppercase;margin-top:2px;white-space:nowrap}.lou-global-search{min-width:250px;max-width:350px;flex:1;position:relative}.lou-global-search input{width:100%;padding:12px 15px;border:1px solid #b9c4b7;border-radius:999px;background:#fffefa;font-size:16px}.site-header nav{background:#fffdf8;border-top:1px solid #eff1eb;overflow:hidden}.site-header .lou-main-nav{max-width:1180px;margin:auto;display:flex;gap:22px;overflow-x:auto;-webkit-overflow-scrolling:touch;scrollbar-width:none;padding:11px 18px 12px!important}.site-header .lou-main-nav::-webkit-scrollbar{display:none}.site-header .lou-main-nav a{flex:0 0 auto;text-decoration:none;color:#315d3f;font-weight:750;white-space:nowrap;padding-bottom:3px;border-bottom:3px solid transparent}.site-header .lou-main-nav a.active{color:#244832;border-bottom-color:#315d3f}.lou-search-popover{display:none;position:absolute;left:0;right:0;top:calc(100% + 7px);z-index:100000;background:#fffdf8;border:1px solid #cbd5c9;border-radius:15px;box-shadow:0 12px 30px rgba(0,0,0,.18);padding:7px;max-height:min(52vh,420px);overflow-y:auto}.lou-search-popover.open{display:block}.lou-search-popover a{display:block;padding:12px 13px;border-radius:10px;text-decoration:none;color:#244832;font-weight:750;border-bottom:1px solid #edf0e9}.lou-search-empty{padding:12px 13px;color:#6b746e}@media(max-width:950px){.lou-unified-topbar{align-items:flex-start;flex-direction:column;gap:12px}.lou-global-search{width:100%;max-width:none;min-width:0}.lou-search-popover{position:fixed;left:18px;right:18px;top:164px;max-height:48vh}}@media(max-width:520px){.lou-unified-topbar .brand img{width:58px!important;height:58px!important}.lou-unified-topbar .brand strong{font-size:clamp(1.35rem,6vw,1.8rem)}.lou-brand-tagline{font-size:.68rem}.site-header .lou-main-nav{gap:20px;padding-left:16px!important;padding-right:16px!important}}`;document.head.appendChild(s);}}
function search(){const input=document.getElementById('topSearch');if(!input||document.getElementById('louSearchPopover'))return;const pop=document.createElement('div');pop.id='louSearchPopover';pop.className='lou-search-popover';input.parentElement.appendChild(pop);function matches(v){const q=v.trim().toLowerCase();if(!q)return[];const existing=[...document.querySelectorAll('.search-results a')].map(x=>[(x.dataset.search||'')+' '+x.textContent,x.getAttribute('href'),x.textContent]);const all=[...existing,...EXTRA_SEARCH];const seen=new Set();return all.filter(x=>(x[0]||'').toLowerCase().includes(q)||(x[2]||'').toLowerCase().includes(q)).filter(x=>{if(seen.has(x[1]))return false;seen.add(x[1]);return true;});}function render(v){const q=v.trim();if(!q){pop.classList.remove('open');pop.innerHTML='';return[]}if(!isHome()){pop.innerHTML=`<a href="index.html?search=${encodeURIComponent(q)}">Search the full Garden Guide for “${q.replace(/[<>&"]/g,'')}”</a>`;pop.classList.add('open');return[]}const m=matches(q);pop.innerHTML=m.length?m.map(x=>`<a href="${x[1]}">${x[2]}</a>`).join(''):'<div class="lou-search-empty">No matching plant or topic found.</div>';pop.classList.add('open');return m;}input.addEventListener('input',e=>render(e.target.value));input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();const q=input.value.trim();if(!q)return;if(!isHome()){location.href=`index.html?search=${encodeURIComponent(q)}`;return;}const m=matches(q);if(m.length)location.href=m[0][1];}else if(e.key==='Escape')pop.classList.remove('open');});document.addEventListener('click',e=>{if(!input.parentElement.contains(e.target))pop.classList.remove('open');});if(isHome()){const q=new URLSearchParams(location.search).get('search');if(q){input.value=q;setTimeout(()=>render(q),0);}}}
function home(){if(!isHome())return;const tasks=['<strong>Sunflower:</strong> approximately 12 feet tall; continue documenting seed development.','<strong>Blueberry cuttings:</strong> continue gradual hardening-off and watch closely for wilting.','Harvest ripe tomatoes, peppers, beans, carrots and summer squash regularly.','Inspect pumpkin, squash and cucumber foliage for beetles, eggs and new feeding damage.'];document.querySelectorAll('.today-strip .task-list li').forEach((x,i)=>{if(tasks[i])x.innerHTML=tasks[i];});const b=document.querySelector('.update-banner');if(b){b.setAttribute('aria-label','Latest garden update dated August 20, 2026');const h=b.querySelector('h2'),p=b.querySelector('p');if(h)h.textContent='Latest Garden Update · August 20, 2026';if(p)p.textContent='New photographs now document late-summer harvests, dahlias, Morning Glory, String Beans, Peonies, Big and Small Jade plants, Oregano, Butternut Squash, pumpkin progress, milkweed tussock moth caterpillars, and the approximately 12-foot sunflower.';}const f=document.querySelector('footer');if(f)f.textContent='Lou’s Garden Guide · Updated August 20, 2026';}
function quick(){if(isHome()||document.getElementById('louQuickNavigation'))return;const s=document.createElement('style');s.textContent='.lou-quick-nav{position:fixed;left:max(12px,env(safe-area-inset-left));bottom:max(12px,env(safe-area-inset-bottom));z-index:99999;display:flex;gap:10px;padding:8px;border-radius:18px;background:rgba(255,255,255,.96);box-shadow:0 5px 22px rgba(0,0,0,.28);border:1px solid rgba(31,79,45,.22)}.lou-quick-nav button,.lou-quick-nav a{min-height:48px;display:inline-flex;align-items:center;justify-content:center;gap:6px;padding:10px 14px;border:0;border-radius:13px;background:#245c36;color:#fff!important;font:700 16px system-ui;text-decoration:none!important}';document.head.appendChild(s);const n=document.createElement('nav');n.id='louQuickNavigation';n.className='lou-quick-nav';n.innerHTML='<button type="button" aria-label="Go back">← <span>Back</span></button><a href="index.html" aria-label="Go home">⌂ <span>Home</span></a>';n.querySelector('button').onclick=()=>history.length>1?history.back():location.assign('index.html');document.body.appendChild(n);}
function init(){header();home();search();quick();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();